services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.8.10
    container_name: open-webui
    restart: "no"
    ports:
      - "3000:3000"
      - "8001:8001"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - PORT=3000
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
  
  anything-llm:
    image: mintplexlabs/anythingllm
    container_name: anything-llm
    restart: "no"
    ports:
      - "3001:3001"
      - "8002:8002"
    environment:
      - STORAGE_DIR=/app/server/storage
    volumes:
      - anythingllm_storage:/app/server/storage

volumes:
  open-webui:
    external: true
  anythingllm_storage:
    external: true
